<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$config=load_config();configure_cors($config);$pdo=database($config);$method=$_SERVER['REQUEST_METHOD']??'GET';$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$pos=strpos($path,'/api/v1');if($pos!==false)$path=substr($path,$pos);$path='/'.trim($path,'/');
try{
 if($method==='POST'&&$path==='/api/v1/cards')create_card($pdo,$config,read_json_body());
 if($method==='GET'&&preg_match('#^/api/v1/cards/(s_[A-Za-z0-9_-]{43})$#',$path,$m))get_card($pdo,$m[1]);
 if($method==='GET'&&preg_match('#^/api/v1/cards/(s_[A-Za-z0-9_-]{43})/public-results$#',$path,$m))get_public_results($pdo,$config,$m[1]);
 if($method==='POST'&&preg_match('#^/api/v1/cards/(s_[A-Za-z0-9_-]{43})/responses$#',$path,$m))create_response($pdo,$config,$m[1],read_json_body());
 if($method==='POST'&&$path==='/api/v1/management/session')open_management_session($pdo,$config);
 if($method==='GET'&&$path==='/api/v1/manage/card')get_managed_card($pdo,$config);
 if($method==='GET'&&$path==='/api/v1/manage/card/responses')list_managed_responses($pdo,$config);
 if($method==='PATCH'&&$path==='/api/v1/manage/card/settings')update_card_settings($pdo,$config,read_json_body());
 error_response(404,'NOT_FOUND','요청한 API를 찾을 수 없습니다.');
}catch(PDOException $e){error_log('Gunnam DB error; requestId='.request_id().'; state='.$e->getCode());error_response(500,'INTERNAL_ERROR','요청을 처리하지 못했습니다.');}catch(Throwable $e){error_log('Gunnam API error; requestId='.request_id().'; type='.get_class($e));error_response(500,'INTERNAL_ERROR','요청을 처리하지 못했습니다.');}

function create_card(PDO $db,array $cfg,array $in):never{
 assert_known_fields($in,['deliveryMode','responseVisibility','questionText','acceptButtonText','rejectButtonText','acceptResultText','rejectResultText']);
 $visibility=$in['responseVisibility']??'owner_only';if(($in['deliveryMode']??null)!=='link'||!is_string($visibility)||!in_array($visibility,response_visibility_values(),true))error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['deliveryMode'=>['link여야 합니다.'],'responseVisibility'=>['owner_only, counts_only, all_responses 중 하나여야 합니다.']]);
 $pub=['questionText'=>text_field($in,'questionText',500,true),'acceptButtonText'=>text_field($in,'acceptButtonText',30)??'좋아요','rejectButtonText'=>text_field($in,'rejectButtonText',30)??'싫어요','acceptResultText'=>text_field($in,'acceptResultText',500),'rejectResultText'=>text_field($in,'rejectResultText',500)];$key=idempotency_key();rate_limit($cfg,'card-create','global',10,600);$request=$pub+['deliveryMode'=>'link','responseVisibility'=>$visibility];$rh=hash('sha256',json_encode($request,GUNNAM_JSON_FLAGS|JSON_THROW_ON_ERROR));$share=derived_token('s_','card-share',$key,$cfg['hmac_secret']);$manage=derived_token('m_','card-management',$key,$cfg['hmac_secret']);$payload=$pub+['_meta'=>['idempotencyKeyHash'=>hash('sha256',$key),'requestHash'=>$rh]];
 $find=$db->prepare("SELECT * FROM gunnam_post WHERE post_type='card' AND share_token_hash=:h LIMIT 1");$find->execute([':h'=>token_digest($share)]);if($row=$find->fetch())existing_card($row,$rh,$share,$manage,$cfg);
 try{$q=$db->prepare("INSERT INTO gunnam_post(post_type,parent_id,account_id,payload,delivery_mode,response_visibility,share_token_hash,management_token_hash,response_type,public_consent,edit_token_hash,status)VALUES('card',NULL,NULL,:p,'link',:v,:s,:m,NULL,0,NULL,'open')");$q->execute([':p'=>json_encode($payload,GUNNAM_JSON_FLAGS|JSON_THROW_ON_ERROR),':v'=>$visibility,':s'=>token_digest($share),':m'=>token_digest($manage)]);}catch(PDOException $e){if((string)$e->getCode()!=='23000')throw $e;$find->execute([':h'=>token_digest($share)]);if(!($row=$find->fetch()))throw $e;existing_card($row,$rh,$share,$manage,$cfg);}
 $find->execute([':h'=>token_digest($share)]);created_card(201,$find->fetch(),$share,$manage,$cfg);
}
function existing_card(array $r,string $rh,string $s,string $m,array $c):never{if((decode_payload($r['payload'])['_meta']['requestHash']??'')!==$rh)error_response(409,'IDEMPOTENCY_CONFLICT','같은 멱등성 키가 다른 요청에 사용되었습니다.');created_card(200,$r,$s,$m,$c);}
function created_card(int $status,array $r,string $s,string $m,array $c):never{$b=rtrim($c['app_base_url'],'/');success_response($status,['card'=>card_dto($r),'shareUrl'=>$b.'/c/'.rawurlencode($s),'managementUrl'=>$b.'/manage#token='.rawurlencode($m)]);}
function get_card(PDO $db,string $t):never{header('Referrer-Policy: no-referrer');$q=$db->prepare("SELECT * FROM gunnam_post WHERE post_type='card' AND share_token_hash=:h LIMIT 1");$q->execute([':h'=>token_digest($t)]);$r=$q->fetch();if(!$r||$r['status']==='deleted')error_response(404,'CARD_NOT_FOUND','카드를 찾을 수 없습니다.');if($r['status']==='closed')error_response(410,'CARD_CLOSED','응답이 마감된 카드입니다.');$visibility=normalized_visibility($r['response_visibility']??null);$kind=match($visibility){'counts_only'=>'counts','all_responses'=>'responses',default=>'private'};success_response(200,['card'=>card_dto($r),'responseNotice'=>response_notice($visibility),'publicResults'=>['available'=>$visibility!=='owner_only','kind'=>$kind],'consent'=>['required'=>$visibility==='all_responses','defaultValue'=>false]]);}

function create_response(PDO $db,array $cfg,string $token,array $in):never{
 assert_known_fields($in,['responseType','nickname','replyText','publicConsent','visibilityAtSubmission']);$type=$in['responseType']??null;if(!in_array($type,['accept','reject'],true))error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['responseType'=>['수락 또는 거절을 선택해주세요.']]);$submittedVisibility=$in['visibilityAtSubmission']??null;if(!is_string($submittedVisibility)||!in_array($submittedVisibility,response_visibility_values(),true))error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['visibilityAtSubmission'=>['현재 카드의 공개 범위여야 합니다.']]);$nick=text_field($in,'nickname',50);$reply=text_field($in,'replyText',1000);$hasConsent=array_key_exists('publicConsent',$in);$consent=$in['publicConsent']??false;if($hasConsent&&!is_bool($consent))error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['publicConsent'=>['true 또는 false여야 합니다.']]);$key=idempotency_key();$lookup=$db->prepare("SELECT id FROM gunnam_post WHERE post_type='card' AND share_token_hash=:h AND status<>'deleted' LIMIT 1");$lookup->execute([':h'=>token_digest($token)]);$rateCard=$lookup->fetch();if(!$rateCard)error_response(404,'CARD_NOT_FOUND','카드를 찾을 수 없습니다.');rate_limit($cfg,'response-create',(string)$rateCard['id'],20,600);
 $db->beginTransaction();try{$cq=$db->prepare("SELECT * FROM gunnam_post WHERE post_type='card' AND share_token_hash=:h LIMIT 1 FOR UPDATE");$cq->execute([':h'=>token_digest($token)]);$card=$cq->fetch();if(!$card||$card['status']==='deleted'){$db->rollBack();error_response(404,'CARD_NOT_FOUND','카드를 찾을 수 없습니다.');}if($card['status']!=='open'){$db->rollBack();error_response(410,'CARD_CLOSED','응답이 마감된 카드입니다.');}$visibility=normalized_visibility($card['response_visibility']??null);if($submittedVisibility!==$visibility){$db->rollBack();error_response(409,'VISIBILITY_CHANGED','답변 공개 범위가 변경되었습니다. 카드를 다시 확인해주세요.');}if($visibility==='all_responses'&&!$hasConsent){$db->rollBack();error_response(422,'PUBLIC_CONSENT_REQUIRED','공개 동의 또는 비동의를 선택해주세요.');}if($visibility!=='all_responses'&&$consent===true){$db->rollBack();error_response(422,'PUBLIC_CONSENT_NOT_ALLOWED','현재 공개 범위에서는 공개 동의를 받을 수 없습니다.');}$consent=$visibility==='all_responses'&&$consent===true;$norm=['responseType'=>$type,'nickname'=>$nick,'replyText'=>$reply,'publicConsent'=>$consent,'visibilityAtSubmission'=>$visibility];$rh=hash('sha256',json_encode($norm,GUNNAM_JSON_FLAGS|JSON_THROW_ON_ERROR));$marker=hash_hmac('sha256','response-edit'."\0".$card['id']."\0".$key,$cfg['hmac_secret']);$old=$db->prepare("SELECT * FROM gunnam_post WHERE post_type='response' AND parent_id=:c AND edit_token_hash=:m LIMIT 1");$old->bindValue(':c',(int)$card['id'],PDO::PARAM_INT);$old->bindValue(':m',$marker);$old->execute();if($r=$old->fetch()){$db->commit();if((decode_payload($r['payload'])['_meta']['requestHash']??'')!==$rh)error_response(409,'IDEMPOTENCY_CONFLICT','같은 멱등성 키가 다른 요청에 사용되었습니다.');created_response(200,$r,$card);}$payload=['nickname'=>$nick,'replyText'=>$reply,'visibilityAtSubmission'=>$visibility,'_meta'=>['idempotencyKeyHash'=>hash('sha256',$key),'requestHash'=>$rh]];$q=$db->prepare("INSERT INTO gunnam_post(post_type,parent_id,account_id,payload,delivery_mode,response_visibility,share_token_hash,management_token_hash,response_type,public_consent,edit_token_hash,status)VALUES('response',:c,NULL,:p,NULL,NULL,NULL,NULL,:t,:consent,:m,'open')");$q->bindValue(':c',(int)$card['id'],PDO::PARAM_INT);$q->bindValue(':p',json_encode($payload,GUNNAM_JSON_FLAGS|JSON_THROW_ON_ERROR));$q->bindValue(':t',$type);$q->bindValue(':consent',$consent?1:0,PDO::PARAM_INT);$q->bindValue(':m',$marker);$q->execute();$id=$db->lastInsertId();$rq=$db->prepare('SELECT * FROM gunnam_post WHERE id=:id');$rq->execute([':id'=>$id]);$r=$rq->fetch();$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}created_response(201,$r,$card);
}
function created_response(int $s,array $r,array $card):never{$p=decode_payload($r['payload']);$cp=decode_payload($card['payload']);$text=$r['response_type']==='accept'?($cp['acceptResultText']??$cp['acceptButtonText']??'좋아요'):($cp['rejectResultText']??$cp['rejectButtonText']??'싫어요');success_response($s,['response'=>['id'=>(string)$r['id'],'responseType'=>$r['response_type'],'nickname'=>$p['nickname']??null,'replyText'=>$p['replyText']??null,'publicConsent'=>(bool)$r['public_consent'],'createdAt'=>utc_datetime($r['created_at'])],'result'=>['text'=>$text]]);}

function open_management_session(PDO $db,array $cfg):never{$t=bearer_token();$q=$db->prepare("SELECT id FROM gunnam_post WHERE post_type='card' AND management_token_hash=:h AND status<>'deleted' LIMIT 1");$q->execute([':h'=>token_digest($t)]);$r=$q->fetch();if(!$r)error_response(410,'MANAGEMENT_TOKEN_INVALID','관리 링크가 유효하지 않습니다.');start_management_session($cfg);session_regenerate_id(true);$_SESSION=['card_id'=>(string)$r['id'],'expires_at'=>time()+43200];header('Cache-Control: no-store');http_response_code(204);exit;}
function managed_id(array $cfg):int{header('Cache-Control: private, no-store');header('Referrer-Policy: no-referrer');start_management_session($cfg);if(!isset($_SESSION['card_id'],$_SESSION['expires_at'])||$_SESSION['expires_at']<time()){$_SESSION=[];error_response(401,'MANAGEMENT_AUTH_REQUIRED','관리 세션이 필요합니다.');}return(int)$_SESSION['card_id'];}
function get_managed_card(PDO $db,array $cfg):never{$id=managed_id($cfg);$q=$db->prepare("SELECT * FROM gunnam_post WHERE id=:id AND post_type='card' AND status<>'deleted'");$q->bindValue(':id',$id,PDO::PARAM_INT);$q->execute();$r=$q->fetch();if(!$r)error_response(404,'MANAGED_CARD_NOT_FOUND','관리 중인 카드를 찾을 수 없습니다.');success_response(200,['card'=>card_dto($r)]);}
function list_managed_responses(PDO $db,array $cfg):never{$id=managed_id($cfg);$limit=isset($_GET['limit'])?filter_var($_GET['limit'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>50]]):20;if($limit===false)error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['limit'=>['1~50 사이여야 합니다.']]);$cursor=isset($_GET['cursor'])?decode_response_cursor($cfg,(string)$_GET['cursor']):null;$sql="SELECT * FROM gunnam_post WHERE parent_id=:id AND post_type='response' AND status<>'deleted'".($cursor!==null?" AND (created_at<:createdBefore OR (created_at=:createdEqual AND id<:cursorId))":"")." ORDER BY created_at DESC,id DESC LIMIT :lim";$q=$db->prepare($sql);$q->bindValue(':id',$id,PDO::PARAM_INT);if($cursor!==null){$q->bindValue(':createdBefore',$cursor['createdAt']);$q->bindValue(':createdEqual',$cursor['createdAt']);$q->bindValue(':cursorId',(int)$cursor['id'],PDO::PARAM_INT);}$q->bindValue(':lim',$limit+1,PDO::PARAM_INT);$q->execute();$rows=$q->fetchAll();$hasMore=count($rows)>$limit;if($hasMore)$rows=array_slice($rows,0,$limit);$items=array_map(static function(array $r):array{$p=decode_payload($r['payload']);return['id'=>(string)$r['id'],'responseType'=>$r['response_type'],'nickname'=>$p['nickname']??null,'replyText'=>$p['replyText']??null,'publicConsent'=>(bool)$r['public_consent'],'visibilityAtSubmission'=>$p['visibilityAtSubmission']??'owner_only','createdAt'=>utc_datetime($r['created_at'])];},$rows);$last=$hasMore?end($rows):false;$next=$last?encode_response_cursor($cfg,$last['created_at'],(string)$last['id']):null;success_response(200,['items'=>$items,'nextCursor'=>$next]);}

function response_visibility_values():array{return['owner_only','counts_only','all_responses'];}
function normalized_visibility(mixed $value):string{return is_string($value)&&in_array($value,response_visibility_values(),true)?$value:'owner_only';}
function response_notice(string $visibility):string{return match($visibility){
 'counts_only'=>'수락·거절 결과 숫자는 공유 링크를 아는 사람에게 공개돼요. 닉네임과 추가 의견은 작성자만 확인할 수 있어요.',
 'all_responses'=>'공개에 동의하면 선택, 닉네임과 추가 의견이 공유 링크를 아는 사람에게 공개돼요. 동의하지 않아도 답변할 수 있어요.',
 default=>'작성자만 답변을 확인할 수 있어요. 선택, 닉네임과 추가 의견은 다른 사람에게 공개되지 않아요.'
};}
function public_response_counts(PDO $db,int $cardId):array{$q=$db->prepare("SELECT COUNT(*) AS total_count,COALESCE(SUM(response_type='accept'),0) AS accept_count,COALESCE(SUM(response_type='reject'),0) AS reject_count FROM gunnam_post WHERE parent_id=:id AND post_type='response' AND status<>'deleted' AND response_type IN ('accept','reject')");$q->bindValue(':id',$cardId,PDO::PARAM_INT);$q->execute();$r=$q->fetch()?:[];return['total'=>(int)($r['total_count']??0),'accept'=>(int)($r['accept_count']??0),'reject'=>(int)($r['reject_count']??0)];}
function public_response_dto(array $row):array{$payload=decode_payload($row['payload']);return['responseType'=>$row['response_type'],'nickname'=>$payload['nickname']??null,'replyText'=>$payload['replyText']??null];}
function try_decode_public_cursor(array $config,string $cursor):?array{if(strlen($cursor)>1024||!preg_match('/^([A-Za-z0-9_-]+)\.([A-Za-z0-9_-]+)$/',$cursor,$matches))return null;$expected=hash_hmac('sha256','responses-cursor'."\0".$matches[1],$config['hmac_secret'],true);$given=base64url_decode($matches[2]);$json=base64url_decode($matches[1]);if($given===false||$json===false||!hash_equals($expected,$given))return null;try{$data=json_decode($json,true,4,JSON_THROW_ON_ERROR);}catch(JsonException $e){return null;}if(!is_array($data)||!isset($data['createdAt'],$data['id'])||!is_string($data['createdAt'])||!preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/',$data['createdAt'])||!is_string($data['id'])||!preg_match('/^[1-9][0-9]*$/',$data['id']))return null;return $data;}
function get_public_results(PDO $db,array $cfg,string $token):never{
 header('Referrer-Policy: no-referrer');$digest=token_digest($token);$preflight=$db->prepare("SELECT id FROM gunnam_post WHERE post_type='card' AND share_token_hash=:h AND status<>'deleted' LIMIT 1");$preflight->execute([':h'=>$digest]);$knownCard=$preflight->fetch();if(!$knownCard)error_response(404,'CARD_NOT_FOUND','카드를 찾을 수 없습니다.');rate_limit($cfg,'public-responses',(string)$knownCard['id'],60,600);$db->beginTransaction();try{$q=$db->prepare("SELECT id,response_visibility,status FROM gunnam_post WHERE post_type='card' AND share_token_hash=:h LIMIT 1 LOCK IN SHARE MODE");$q->execute([':h'=>$digest]);$card=$q->fetch();if(!$card||$card['status']==='deleted'){$db->rollBack();error_response(404,'CARD_NOT_FOUND','카드를 찾을 수 없습니다.');}$visibility=normalized_visibility($card['response_visibility']??null);
 if($visibility==='owner_only'){$db->commit();success_response(200,['kind'=>'private']);}
 if($visibility==='counts_only'){if(isset($_GET['cursor'])){$db->rollBack();error_response(422,'UNKNOWN_FIELD','집계 조회에는 cursor를 사용할 수 없습니다.',['cursor'=>['사용할 수 없는 필드입니다.']]);}$result=['kind'=>'counts','counts'=>public_response_counts($db,(int)$card['id'])];$db->commit();success_response(200,$result);}
 $limit=isset($_GET['limit'])?filter_var($_GET['limit'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>50]]):20;if($limit===false){$db->rollBack();error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['limit'=>['1~50 사이여야 합니다.']]);}$cursor=isset($_GET['cursor'])?try_decode_public_cursor($cfg,(string)$_GET['cursor']):null;if(isset($_GET['cursor'])&&$cursor===null){$db->rollBack();error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['cursor'=>['유효하지 않은 cursor입니다.']]);}$sql="SELECT id,response_type,payload,created_at FROM gunnam_post WHERE parent_id=:id AND post_type='response' AND status<>'deleted' AND response_type IN ('accept','reject') AND public_consent=1".($cursor!==null?" AND (created_at<:createdBefore OR (created_at=:createdEqual AND id<:cursorId))":"")." ORDER BY created_at DESC,id DESC LIMIT :lim";$items=$db->prepare($sql);$items->bindValue(':id',(int)$card['id'],PDO::PARAM_INT);if($cursor!==null){$items->bindValue(':createdBefore',$cursor['createdAt']);$items->bindValue(':createdEqual',$cursor['createdAt']);$items->bindValue(':cursorId',(int)$cursor['id'],PDO::PARAM_INT);}$items->bindValue(':lim',$limit+1,PDO::PARAM_INT);$items->execute();$rows=$items->fetchAll();$hasMore=count($rows)>$limit;if($hasMore)$rows=array_slice($rows,0,$limit);$last=$hasMore?end($rows):false;$result=['kind'=>'responses','items'=>array_map('public_response_dto',$rows),'nextCursor'=>$last?encode_response_cursor($cfg,$last['created_at'],(string)$last['id']):null];$db->commit();success_response(200,$result);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function update_card_settings(PDO $db,array $cfg,array $input):never{
 $cardId=managed_id($cfg);assert_known_fields($input,['responseVisibility']);$visibility=$input['responseVisibility']??null;if(!is_string($visibility)||!in_array($visibility,response_visibility_values(),true))error_response(422,'VALIDATION_FAILED','입력값을 확인해주세요.',['responseVisibility'=>['owner_only, counts_only, all_responses 중 하나여야 합니다.']]);
 $db->beginTransaction();try{$card=$db->prepare("SELECT * FROM gunnam_post WHERE id=:id AND post_type='card' AND status<>'deleted' FOR UPDATE");$card->bindValue(':id',$cardId,PDO::PARAM_INT);$card->execute();if(!$card->fetch()){$db->rollBack();error_response(404,'MANAGED_CARD_NOT_FOUND','관리 중인 카드를 찾을 수 없습니다.');}$q=$db->prepare("UPDATE gunnam_post SET response_visibility=:visibility WHERE id=:id AND post_type='card' AND status<>'deleted'");$q->bindValue(':visibility',$visibility);$q->bindValue(':id',$cardId,PDO::PARAM_INT);$q->execute();$card->execute();$row=$card->fetch();$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}success_response(200,['card'=>card_dto($row)]);
}
